name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.14"
      - name: Install dependencies
        run: |
          make uv-setup
      - name: Run unit and integration tests
        run: |
          make pytest